Multas/Multas/Models/Agentes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multas.Models {
   public class Agentes {

      /// atributos:
      /// - nº agente
      /// - nome
      /// - esquadra
      /// - foto

      public Agentes() {
         // criar o objeto 'ListaDeMultas'
         ListaDeMultas = new HashSet<Multas>();
      }

      [Key]
      public int ID { get; set; }

      [Required(ErrorMessage = "o Nome é de preenchimento obrigatório.")]
      [StringLength(40)]
      [RegularExpression("[A-ZÁÉÍÓÚÂ][a-záéíóúàèìòùäëïöüãõâêîôûçñ]+(( | e | de | da | das | do | dos |-|'|d')[A-ZÁÉÍÓÚÂ][a-záéíóúàèìòùäëïöüãõâêîôûçñ]*){1,3}",
                         ErrorMessage = "só são aceites palavras, começadas por Maiúscula, " +
                                       "separadas por um espeço em branco.")]
      public string Nome { get; set; }

      [Required(ErrorMessage = "a Esquadra é de preenchimento obrigatório.")]
      [StringLength(30)]
      //   [RegularExpression("Torres Novas|Tomar|Entroncamento",
      //                      ErrorMessage = " só é aceite Torres Novas ou Tomar ou Entroncamento")]
      public string Esquadra { get; set; }

      [StringLength(40)]
      public string Fotografia { get; set; }

      // lista das multas associadas ao Agente
      public virtual ICollection<Multas> ListaDeMultas { get; set; }
      // a palavra 'virtual' ativa o chamado Lazy Loading

      //*************************************************************
      // definir uma "chave forasteira" para a tabela da autenticação
      //   [Required]
      public string UserName { get; set; }

   }
}

Multas/Multas/Controllers/AgentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multas.Models;

namespace Multas.Controllers {

   [Authorize] // só pessoas autenticadas podem aceder ao seu conteúdo
   public class AgentesController : Controller {
      private MultasDB db = new MultasDB();

      // GET: Agentes
      [Authorize(Roles = "RecursosHumanos,Agente")] // só as pessoas que forem
      // do role 'Agente' OU do role 'RecursosHumanos' podem aceder

      //[Authorize(Roles = "Agente")]           // só tem acesso as pessoas que forem 
      //[Authorize(Roles = "RecursosHumanos")]  // de RecursosHumanos E Agente
      public ActionResult Index() {

         // LINQ
         // SELECT * FROM Agentes ORDER BY ID DESC   <--- só as pessoas dos recursos humanos
         var listaDeAgentes = db.Agentes
                                .OrderByDescending(a => a.ID)
                                .ToList();

         // se for apenas agente
         //SELECT * FROM Agente WHERE UserName = username da pessoa autenticada
         if(!User.IsInRole("RecursosHumanos")) {
            // vou restringir a listagem inicial apenas aos dados do Agente
            //  listaDeAgentes = listaDeAgentes.Where(a => a.UserName == User.Identity.Name).ToList();

            // redirecionar para página dos detalhes
            int idAgente = db.Agentes
                           .Where(a => a.UserName == User.Identity.Name)
                           .FirstOrDefault()
                           .ID;
            return RedirectToAction("Details", new { id = idAgente });


         }

         return View(listaDeAgentes);
      }

      // GET: Agentes/Details/5
      public ActionResult Details(int? id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         Agentes agente = db.Agentes.Find(id);

         if(agente == null) {
            return HttpNotFound();
         }

         /// posso aceder aos dados dos agentes, quando:
         ///   - for do role 'recursos humanos'
         ///   - for do role ' gestor multas'
         ///   - for o dono dos dados
         if(User.IsInRole("RecursosHumanos") ||
            User.IsInRole("GestorMultas") ||
            agente.UserName == User.Identity.Name) {
            // envia os dados do AGENTE para a View
            return View(agente);
         }
         else{
            // estou a tentar aceder a dados não autorizados
            return RedirectToAction("Index");
         }
      }

      // GET: Agentes/Create
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult Create() {
         return View();
      }

      // POST: Agentes/Create
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult Create([Bind(Include = "Nome,Esquadra")] Agentes agente,
                                 HttpPostedFileBase fotografia) {

         // vars auxiliares
         string caminho = "";
         bool imagemValida = false;

         /// foi fornecido um ficheiro?
         if(fotografia == null) {
            // a foto não existe
            // vou atribuir uma fotografia por defeito
            agente.Fotografia = "nouser.jpg";
         }
         else {
            // existe ficheiro
            /// é uma imagem (fotografia)?
            // aceitamos JPEG e PNG
            if(fotografia.ContentType == "image/jpeg" ||
               fotografia.ContentType == "image/png") {
               // estamos perante uma Foto válida
               /// se é fotografia, 
               ///     guardar a imagem e 
               ///       - definir um nome
               Guid g;
               g = Guid.NewGuid();
               string extensaoDoFicheiro = Path.
                                           GetExtension(fotografia.FileName).
                                           ToLower();
               string nomeFicheiro = g.ToString() + extensaoDoFicheiro;

               ///       - definir um local onde a guardar
               caminho = Path.Combine(Server.MapPath("~/Imagens/"), nomeFicheiro);

               ///     associar ao agente
               agente.Fotografia = nomeFicheiro;

               // marca o ficheiro como válido
               imagemValida = true;
            }
            else {
               /// se não é um ficheiro do tipo imagem (JPEG ou PNG), 
               ///     atribuir ao agente uma 'imagem por defeito'
               agente.Fotografia = "nouser.jpg";
            }
         }

         // avalia se os dados fornecidos estão de acordo com o modelo
         if(ModelState.IsValid) {
            // adicionar os dados do novo Agente ao Modelo
            db.Agentes.Add(agente);
            try {
               // guardar os dados na BD
               db.SaveChanges();
               // guardar a imagem no disco rígido do servidor
               if(imagemValida) fotografia.SaveAs(caminho);
               // redirecionar o utilizador para a página de INDEX
               return RedirectToAction("Index");
            }
            catch(Exception) {
               ModelState.AddModelError("", "Ocorreu um erro desconhecido. " +
                                            "Pedimos deculpa pela ocorrência.");
            }
         }
         // se cheguei aqui é pq alguma coisa correu mal...
         return View(agente);
      }

      // GET: Agentes/Edit/5
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult Edit(int? id) {
         if(id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Agentes agentes = db.Agentes.Find(id);
         if(agentes == null) {
            return HttpNotFound();
         }
         return View(agentes);
      }

      // POST: Agentes/Edit/5
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult Edit([Bind(Include = "ID,Nome,Esquadra,Fotografia")] Agentes agentes) {
         if(ModelState.IsValid) {
            db.Entry(agentes).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(agentes);
      }

      // GET: Agentes/Delete/5
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult Delete(int? id) {

         /// o ID é nulo se:
         ///   - há um erro no programa
         ///   - há um 'xico experto' a tentar a sua sorte
         /// redireciono o utilizador para a página de INDEX
         if(id == null) {
            return RedirectToAction("Index");
            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         // procura os dados do Agente associado ao ID fornecido
         Agentes agente = db.Agentes.Find(id);

         /// o 'agente' é nulo se:
         ///   - há um erro no programa
         ///   - há um 'xico experto' a tentar a sua sorte
         /// redireciono o utilizador para a página de INDEX
         if(agente == null) {
            return RedirectToAction("Index");
            //return HttpNotFound();
         }

         /// para evitar 'trocas' maliciosa do 'agente'
         /// guardar o ID do agente, para futura comparação
         /// - num cookie cifrado
         /// - numa var. de sessão (não funciona no Asp .Net Core)
         /// - noutro recurso válido...
         Session["IdAgente"] = agente.ID;
         Session["acao"] = "Agentes/Delete";

         //  envia para a View os dados do Agente encontrado
         return View(agente);
      }

      // POST: Agentes/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      [Authorize(Roles = "RecursosHumanos")]
      public ActionResult DeleteConfirmed(int? id) {

         /// o ID é nulo se:
         ///   - há um erro no programa
         ///   - há um 'xico experto' a tentar a sua sorte
         /// redireciono o utilizador para a página de INDEX
         if(id == null) {
            return RedirectToAction("Index");
            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         // será que o ID do agente que aqui á fornecido
         // é o ID do agente apresentado no ecrã?
         if(id != (int)Session["IdAgente"] ||
            (string)Session["acao"] != "Agentes/Delete") {
            // redireciono o utilizador para a página de INDEX
            return RedirectToAction("Index");
         }


         // limpar o valor das Var. Sessão, porque não preciso mais delas
         Session["IdAgente"] = "";
         Session["acao"] = "";

         // procurar os dados do Agente a remover
         Agentes agente = db.Agentes.Find(id);
         //   Agentes agente = db.Agentes.Find((int)Session["IdAgente"]);

         /// o 'agente' é nulo se:
         ///   - há um erro no programa
         ///   - há um 'xico experto' a tentar a sua sorte
         /// redireciono o utilizador para a página de INDEX
         if(agente == null) {
            return RedirectToAction("Index");
            //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         try {
            // remove os dados do Agente do Modelo
            db.Agentes.Remove(agente);
            // consolida a remoção da BD
            db.SaveChanges();
         }
         catch(Exception) {
            // prepara mensagem de erro a ser enviada para o utilizador
            ModelState.AddModelError("", "ocorreu um erro com a remoção do agente " +

Multas/Multas/Views/Agentes/Create.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Criar novo Agente";
}

<h2>Adicionar Agente</h2>


@using (Html.BeginForm("Create",
                       "Agentes",
                       FormMethod.Post,
                       new { enctype= "multipart/form-data"}   ))
{


    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

            <input type="file" accept=".jpg,.png" name="fotografia" />

                @*@Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Multas/Multas/Views/Agentes/Delete.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Remover Agente";
}

<h2>Remover um Agente da Base de Dados</h2>

<h3>Tem a certeza que quer remover este agente?</h3>
<div>
 
   <hr />

   @Html.ValidationSummary(true, "", new { @class = "text-danger" })

   <dl class="dl-horizontal">
      <dt>
         @Html.DisplayNameFor(model => model.Nome)
      </dt>
      <dd>
         @Html.DisplayFor(model => model.Nome)
      </dd>

      <dt>
         @Html.DisplayNameFor(model => model.Esquadra)
      </dt>
      <dd>
         @Html.DisplayFor(model => model.Esquadra)
      </dd>

      <dt>
         @Html.DisplayNameFor(model => model.Fotografia)
      </dt>
      <dd>
         @*     <img src="~/Imagens/@Html.DisplayFor(model => model.Fotografia)" alt="" title="" width="150"/><br />*@
         <img src="~/Imagens/@Model.Fotografia" alt="" title="" width="150" />

      </dd>

   </dl>

   @using(Html.BeginForm()) {
      @Html.AntiForgeryToken()

      <div class="form-actions no-color">
         <input type="submit" value="Delete" class="btn btn-default" /> |
         @Html.ActionLink("Back to List", "Index")
      </div>
   }
</div>

Multas/Multas/Views/Agentes/Details.cshtml
@model Multas.Models.Agentes

@{
   ViewBag.Title = "Detalhes";
}

<h2>Detalhes do agente <i>@Model.Nome</i></h2>

<div>
   <hr />
   <dl class="dl-horizontal">
      <dt>
         @Html.DisplayNameFor(model => model.Nome)
      </dt>
      <dd>
         @Html.DisplayFor(model => model.Nome)
      </dd>

      <dt>
         @Html.DisplayNameFor(model => model.Esquadra)
      </dt>
      <dd>
         @Html.DisplayFor(model => model.Esquadra)
      </dd>

      <dt>
         @Html.DisplayNameFor(model => model.Fotografia)
      </dt>
      <dd>
         <img src="~/Imagens/@Html.DisplayFor(model => model.Fotografia)"
              alt="Fotografia do agente @Html.DisplayFor(model => model.Nome)"
              title="@Html.DisplayFor(model => model.Nome)"
              width="150" />

         <img src="~/Imagens/@Model.Fotografia"
              alt="Fotografia do agente @Model.Nome"
              title="@Model.Nome"
              width="150" />
      </dd>
   </dl>
</div>

@* listagem das multas do Agente *@
<div>
   <table class="table">
      <tr>
         @* representa uma primeira linha na tabela, que é o seu cabeçalho *@
         <th>
            @* listar o Nome do atributo DataDaMulta *@
            @Html.DisplayNameFor(m => m.ListaDeMultas.FirstOrDefault().DataDaMulta)
         </th>
         <th>
            @Html.DisplayNameFor(m => m.ListaDeMultas.FirstOrDefault().LocalDaMulta)
         </th>
         <th>
            @Html.DisplayNameFor(m => m.ListaDeMultas.FirstOrDefault().ValorMulta)
         </th>
         <th>
            @Html.DisplayNameFor(m => m.ListaDeMultas.FirstOrDefault().Condutor.Nome)
         </th>
         <th>
            @Html.DisplayNameFor(m => m.ListaDeMultas.FirstOrDefault().Viatura.Matricula)
         </th>
      </tr>
      @* representar as diversas multas do agente *@
      @foreach(var multa in Model.ListaDeMultas) {
         <tr>
            <td>
               @Html.ActionLink(multa.DataDaMulta.ToShortDateString(),
                                "Details",
                                "Multas",
                                new { id = multa.ID },
                                null)
               @*  @multa.DataDaMulta  *@
            </td>
            <td>@multa.LocalDaMulta</td>
            <td>@multa.ValorMulta</td>
            <td>
               @Html.ActionLink(multa.Condutor.Nome,
                              "Details",
                              "Condutores",
                              new { id = multa.Condutor.ID },
                              null)
               @*  @multa.Condutor.Nome  *@
            </td>
            <td>
               @Html.ActionLink(multa.Viatura.Matricula,
                            "Details",
                            "Viaturas",
                            new { id = multa.Viatura.ID },
                            null)
               @*  @multa.Viatura.Matricula  *@
            </td>
         </tr>
      }
   </table>
</div>

<p>
   @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
   @Html.ActionLink("Back to List", "Index")
</p>

Multas/Multas/Views/Agentes/Edit.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agentes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Multas/Multas/Views/Agentes/Index.cshtml
@model IEnumerable<Multas.Models.Agentes>

@{
   ViewBag.Title = "Agentes";
}

<h2>Listagem de Agentes</h2>

@if(User.IsInRole("RecursosHumanos")) {
   <p>
      @Html.ActionLink("Novo Agente", "Create")
   </p>
}

<table class="table">
   <tr>
      <th>
         @* mostra o NOME do atributo *@
         @Html.DisplayNameFor(model => model.Nome)
      </th>
      <th>
         @Html.DisplayNameFor(model => model.Esquadra)
      </th>
      <th>
         @Html.DisplayNameFor(model => model.Fotografia)
      </th>
      <th></th>
   </tr>

   @foreach(var agente in Model) {
      <tr>
         <td>
            @* mostra o CONTEÚDO do atributo *@
            @Html.DisplayFor(modelItem => agente.Nome)
         </td>
         <td>
            @Html.DisplayFor(modelItem => agente.Esquadra)
         </td>
         <td>
            @* Apresentar a imagem de um Agente *@
            <img src="~/Imagens/@agente.Fotografia"
                 alt="imagem do agente @agente.Nome"
                 title="@agente.Nome"
                 width="50" />

            @*@Html.DisplayFor(modelItem => agente.Fotografia)*@
         </td>
         <td>
            @Html.ActionLink("Detalhes", "Details", new { id = agente.ID })
            @if(User.IsInRole("RecursosHumanos")) {
            <text>
               |
               @Html.ActionLink("Editar", "Edit", new { id = agente.ID }) |
               @Html.ActionLink("Apagar", "Delete", new { id = agente.ID })
            </text>
            }
         </td>
      </tr>
   }

</table>